### ISSUE TITLE
Suggestion: make power bar height configurable

### ISSUE THREAD

**Issue by BannZay** [GreenhairTurtle/AshToAsh_BlizzardSkin#1]
Would be great to have an ability to configure power bar height. The only option is to change source files atm https://github.com/KittenBall/AshToAsh_BlizzardSkin/blob/a1cc7f908668a7e78d897f68fc5cb7b464e144b1/Skin.lua#L4

**Comment by KittenBall** [comment]
Because of the game shutdown in China yeasterday, I haven't been online for several months. I'm sorry, this addon is end.

So sorry.

**Comment by BannZay** [comment]
It is already very usefull addon, thank you!

I am sorry about the situation in China =(
